name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: movietix
          MYSQL_USER: movietix
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      # Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Run migrations (optional)
      - name: Run database migrations
        run: |
          php artisan migrate --force || echo "No migrations found"

      # Run tests
      - name: Run tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --testdox
          else
            echo "No PHPUnit tests found, skipping..."
          fi
